# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KTBTaskQueueTests' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KTBTaskQueueTests

  target 'KTBTaskQueueTestsTests' do
    inherit! :search_paths
    pod "KTBTaskQueue", :path => "../KTBTaskQueue.podspec"
    pod 'Kiwi'
  end

end
